version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Getting the Git commit SHA...
      - COMMIT_SHA=$(git rev-parse --short HEAD)
      - echo "Commit SHA is $COMMIT_SHA"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$COMMIT_SHA .
      - docker tag $REPOSITORY_URI:$COMMIT_SHA
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$COMMIT_SHA
